### ISSUE TITLE
Pypi package

### ISSUE THREAD

**Issue by joeyearsley** [deepmind/tensor_annotations#3]
Would it be possible to do releases on pypi? 

We are really enjoying using this package, but currently we need to use workarounds to utilise this package in our CI/CD (as we have extended our bazel builds to utilise poetry), the `:` in the `pip install ... ` means we are having to alter our workflows such as not utilising poetry and installing into our docker images separately. 

Also it makes it hard to ensure we aren't liable to code alterations from the releases, if it's on pypi we can be fixed to a release version.

**Comment by mrahtz** [comment]
Glad you're getting use out of it! I can certainly look into doing released on pypi - stay tuned.

**Comment by mrahtz** [comment]
Right, I've made a first attempt. You wanna try `pip install tensor-annotations tensor-annotations-tensorflow-stubs tensor-annotations-jax-stubs` as needed?

**Comment by joeyearsley** [comment]
That worked, thanks for doing this.
