### ISSUE TITLE
JAX data types and ArrayN annotations don't work as documented

### ISSUE THREAD

**Issue by hylkedonker** [deepmind/tensor_annotations#9]
Hi,

I seem to have a bit of trouble getting the JAX tensor annotations to work. 

**Data types**
Following the docs, when I try to import the JAX data types, it triggers an exception::

```python
import tensor_annotations.jax as tjax
from tensor_annotations.jax import uint8, float32  # Crash!
# Raises: 
# ImportError: cannot import name 'uint8' from 'tensor_annotations.jax' 
```

**Array annotations**
Moreover, when I use a different type instead, I am still unable to annotate, e.g., a `Array2` matrix with a `Batch` and `Time` index:
```python
import jax.numpy as jnp
from tensor_annotations.axes import Batch, Time

a: tjax.Array2[float, Batch, Time] = jnp.zeros([3, 2])  # Crash!
# Raises: 
# TypeError: Too many parameters for <class 'tensor_annotations.jax.Array2'>; actual 3, expected 2
```

**Versions**
I am running the latest version of `tensor_annotations` and `tensor_annotations_jax_stubs` installed through pip:
```
tensor-annotations==1.0.2
tensor-annotations-jax-stubs==1.0.0
```
with `Python 3.10.4` on `Ubuntu 22.04.1 LTS`.

I think that the pip package may be somewhat outdated compared to the code and documentation in the repository.
Any help would be much appreciated!

Thanks,

Hylke

**Comment by mrahtz** [comment]
Ah, sorry about this - I've forgotten to update the Pip version for a while, so that the instructions in the GitHub README are newer than what's true for the Pip version. I'll try to find time to update the Pip version in the next few days.

**Comment by hylkedonker** [comment]
Great, thanks so much. 
Keep up the good work!

**Comment by mrahtz** [comment]
Alright, I just updated the Pip packages. Do you wanna try reinstalling the latest version (should be 2.0.0) and see if it works for you now?

**Comment by hylkedonker** [comment]
I can confirm that it works now. Thanks a lot!
